### ISSUE TITLE
auro-table: create design blueprint

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-table#28]
# General Support Request

The currently released auro-table does not have equal representation in the UI Kit. 

## Support request

Create a design asset that reflects the current UI/UX and design anatomy of the auro-table. 
http://auro.alaskaair.com/components/auro/table

- [x] table presentation
- [x] create blueprint for table
- [x] create blueprint template
- [x] Figma library sandbox to optimize Figma workflow
- [x] auro-table doc framework
- [x] finalize release notes

## Exit criteria

This work will be considered complete when the Figma design asset is able to be added to the Auro UI Kit. 

## Post work

Once this issue is complete, the team needs to discuss when and how this will be added to the auto Doc site.

**Comment by leeejune** [comment]
Does the current auro table have a fixed width property or a "auto" width (either based on the content size or the screen size grid)? In other words, does the width depend on the content size or have a fixed width?

**Comment by blackfalcon** [comment]
@leeejune there is no fixed-width attribute to the auro-table. As stated in the call the other day, I am allowing the table to be a table in HTML and the browser. 

The only thing we are really doing is that at smaller view sizes, the table will scroll allowing for the shape of the table to be created by the content within. 

https://github.com/AlaskaAirlines/auro-table/blob/master/src/style.scss#L27-L28

**Comment by blackfalcon** [comment]
- [ ] words!!!!

**Comment by blackfalcon** [comment]
@leeejune is this task completed? Where is the completed asset that we can link to?

**Comment by leeejune** [comment]
Yes! It has been completed.

[Link to Completed Blueprint](https://www.figma.com/file/7NzNTRt3MFSFo3kwa6lcD0/Table?node-id=447%3A2620)
[Link to Figma Documentation](https://www.figma.com/file/7NzNTRt3MFSFo3kwa6lcD0/Table?node-id=447%3A2620)
