### ISSUE TITLE
Table: symbolize

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-table#4]
# User story

As a designer, I want to be able to reuse the correct table symbol, so I can quickly repeat UIs for my team.

## Outline subtasks or tasks

> List specific steps required to deliver this work.

- [ ] Document the currently developed v1 of the auro-table (see attached image)
- [ ] Add to MASTER branch of UI Kit project
- [ ] Communicate out to designers of update

## Definition of “Done” (exit criteria)

> The story is generally “done” when the user can complete the outlined task, but make sure to define what that is.

This story will be considered complete once the developed asset has been properly documented as a design asset and communicated out to the team. 

## Epic

https://github.com/AlaskaAirlines/auro_docs/issues/98

**Comment by ecommerceUXdesign** [comment]
Feature has been released. @vidalmenAS can you update with the status of design documentation?

**Comment by blackfalcon** [comment]
Unassigned, looking for help

**Comment by blackfalcon** [comment]
Resources are not available to address this task. The intent is to have an FTE designer assigned to Auro to address this and other related work items.
