### ISSUE TITLE
Node-sass and Orion Dependency Migration

### ISSUE THREAD

**Issue by aesthetiques** [AlaskaAirlines/auro-table#66]
# User story

There are multiple components that currently make use of this component, and when attempting to update to the newest auro design sass dependencies, we're seeing dependency tree conflicts due to node-sass and orion dependencies. 

![image](https://user-images.githubusercontent.com/25255197/218595332-0c7fe841-21f3-4351-826f-f1f1438985f1.png)

## Outline subtasks or tasks

> List specific steps required to deliver this work.

- Migrate from orion to latest auro dependencies
- Migrate off of node-sass (I believe we're using dart-sass now?) 

## Definition of “Done” (exit criteria)

- There are no deprecated dependencies in the tree

**Comment by blackfalcon** [comment]
## Spec

1. remove ODS dependencies 
2. Update to Dart-Sass (node 16+ support)
3. The whole test harness and Husky support needs to be updated as well

## Exit criteria 

This issue will be considered complete once the repo can build using Node 18.

**Comment by blackfalcon** [comment]
this issue was addressed with this commit https://github.com/AlaskaAirlines/auro-table/commit/add80c1bb16ec09e9e3316c1ce6f319217d63d8d
